spring.application.name=eureka-server
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false



# Sampling rate (1.0 = 100%, 0.1 = 10%)
management.tracing.sampling.probability=1.0

# Zipkin endpoint
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Optional: Enable tracing for all requests
management.tracing.enabled=true

# Logging correlation (adds trace ID to logs)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]