spring.application.name=fraud
server.port=0
spring.datasource.url=jdbc:postgresql://localhost:5432/fraud
spring.datasource.username=amrox
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Eureka server configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# Enable Eureka client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance-id:${random.value}}
eureka.instance.preferIpAddress=true
# Sampling rate (1.0 = 100%, 0.1 = 10%)
management.tracing.sampling.probability=1.0

# Zipkin endpoint
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Optional: Enable tracing for all requests
management.tracing.enabled=true

# Logging correlation (adds trace ID to logs)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]